version: '3'
services:
  app:
    build: .
    ports:
      - 80:80
    container_name: app-dusha
    volumes:
      - ./app:/src/app
    environment:
      - APP_DB_CONNECTION=mysql
      - APP_DB_HOST=db
      - APP_DB_PORT=3306
      - APP_DB_DATABASE=${MYSQL_DATABASE}
      - APP_DB_USERNAME=${MYSQL_USER}
      - APP_DB_PASSWORD=${MYSQL_PASSWORD}

  npm:
    image: node:current-alpine
    volumes:
      - ./app:/src/app
    entrypoint: ["npm"]
    working_dir: /src/app

  composer:
    build:
      context: .
      dockerfile: .docker/composer/Dockerfile
    volumes:
      - ./app:/src/app
    working_dir: /src/app

  db:
    image: mysql:${MYSQL_VERSION}
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: