version: '3'
services:
  app:
    build: .
    ports:
      - 80:80
    container_name: app-dusha
    volumes:
      - ./app:/src/app

  npm:
    image: node:current-alpine
    volumes:
      - ./app:/src/app
    entrypoint: ["npm"]
    working_dir: /src/app

  composer:
    build:
      context: .
      dockerfile: .docker/composer/Dockerfile
    volumes:
      - ./app:/src/app
    working_dir: /src/app